export const READ_COOKIES = 'READ_COOKIES';
export const READ_COOKIES_COMPLETE = 'READ_COOKIES_COMPLETE';

export const LOG_IN = 'LOG_IN';
export const SET_API_KEY = 'SET_API_KEY';
export const CONFIRM_API_KEY = 'CONFIRM_API_KEY';
export const COMMIT_API_KEY = 'COMMIT_API_KEY';

export const LOG_OUT = 'LOG_OUT';

export const FIND_STOCKS = 'FIND_STOCKS';
export const SEARCH_STOCKS_SUCCESS = 'SEARCH_STOCKS_SUCCESS';
export const SEARCH_STOCKS_FAILURE = 'SEARCH_STOCKS_FAILURE';

export const DASHBOARD = 'DASHBOARD';

export const WITHDRAW_CASH = 'WITHDRAW';
export const DEPOSIT_CASH = 'DESPOSIT';
export const TRADE_STOCK = 'TRADE_STOCK';
